#!/system/bin/sh

if [ "a$2" != "a" ];then
  boosttime=$2
fi

mount -o remount,rw /
GOVERNOR=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
BOOSTTIME_PATH=/sys/devices/system/cpu/cpufreq/$GOVERNOR/boosttime

case "${boosttime}" in
	    500000)  boosttime=500000  
	    ;;
	    1000000)  boosttime=1000000  
	    ;;
	    2000000) boosttime=2000000 
	    ;;
esac

chown system system $BOOSTTIME_PATH
chmod 0660 $BOOSTTIME_PATH 
echo ${boosttime} > $BOOSTTIME_PATH   

mount -o remount,ro /

echo $boosttime
