#!/system/bin/sh

if [ "a$2" != "a" ];then
  cfs_tweaks=$2
fi

mount -o remount,rw /

case "${cfs_tweaks}" in
  0)
    sync
    sysctl -w vm.drop_caches=3 > /dev/null
    sysctl -w vm.drop_caches=0 > /dev/null
    sysctl -w kernel.sched_min_granularity_ns=750000 > /dev/null
    sysctl -w kernel.sched_latency_ns=10000000 > /dev/null
    sysctl -w kernel.sched_wakeup_granularity_ns=2000000 > /dev/null
    ;;
  1)
    sync
    sysctl -w vm.drop_caches=3 > /dev/null
    sysctl -w vm.drop_caches=0 > /dev/null
    sysctl -w kernel.sched_min_granularity_ns=300000 > /dev/null
    sysctl -w kernel.sched_latency_ns=500000 > /dev/null
    sysctl -w kernel.sched_wakeup_granularity_ns=200000 > /dev/null
    ;;
esac;

mount -o remount,ro /

echo $cfs_tweaks
